[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build-clean]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.build-clean-no-encryption]
command = "cargo"
args = ["build", "--no-default-features"]
dependencies = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build-no-encryption]
command = "cargo"
args = ["build", "--no-default-features"]

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.run-no-encryption]
command = "cargo"
args = ["run", "--no-default-features"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.clippy-no-encryption]
command = "cargo"
args = ["clippy", "--no-default-features"]
